[package]
name = "rej"
version = "0.3.1"
edition = "2021"
description = "Minimalistic storage for database"
license = "MIT"

[dev-dependencies]
tempdir = "0.3.7"

[dependencies]
libc = { version = "0.2.166" }
fs4 = { version = "0.11.1" }
memmap2 = { version = "0.9.5" }
thiserror = { version = "2.0" }
parking_lot = { version = "0.12.3" }
memoffset = { version = "0.9.1" }
